### ISSUE TITLE
Make SAR's potentially unable to be removed with delrole command

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#12]
Other staff members have asked for an option to make members unable to remove the "ally" role from themselves through the bot, potentially with a message letting the person know to contact staff. This way, a staff member would definitely be aware of this and cis people would be less likely to get around being clearly visible as such, for safety reasons.

**Comment by catrenelle** [comment]
So what is really being requested:

Modify !addsar <role> <category>
to be more like !addsar <role> <category> <user removable, optional parameter, default = true>

Modify !delrole <role> to check to see if role can be removed. If so, remove it. Otherwise, display message that the specified role cannot be removed except by Administration.

Then you would want to make this specific role set to FALSE for user removable.

Can do, pretty quickly even.

**Comment by catrenelle** [comment]
This is now programmed and awaiting rollout.
