### ISSUE TITLE
!ban command issue

### ISSUE THREAD

**Issue by minkses** [catrenelle/CatBot#16]
Upon using !ban, the bot occasionally replies "Something went wrong :( I probably lack permissions!" for no (to me) discernible reason.
Latest case has been with Lorelei Moira.

**Comment by catrenelle** [comment]
This was my fault due to modifying the database object. I forgot to set the WelcomeMessageID to an unsigned bigint, leaving it as just bigint. This caused !ban to fail when it attempted to fetch user data (since that is now part of user data).

I'm closing this issue, please re-open if you encounter it again.
