### ISSUE TITLE
Add mention to ban log

### ISSUE THREAD

**Issue by FinalFarce** [catrenelle/CatBot#19]
Currently the bot has proper clickable mentions of the user being punished and the staff member that did the command on kicks and warnings, but not on timeouts, bot revocations, or bans. This makes it a lot easier to keep tabs on users and grab them to see username changes and such (if necessary). (IDK i just wish it was consistent o.o)

**Comment by catrenelle** [comment]
This issue cannot be fixed for bans. Any ban that is updated with !reason loses the mention tags and they cannot be re-added. This is because they are no longer with the server. Discord does not let you add mentions for users who are not on the server, so instead it puts them as actual text.

However, for the informational notices I added, I'll have those fixed to use CreateLog instead of CreateLogReason so that they get proper mention. :)
